version: '3'
services:
  server:
    build: .
    command: yarn start:dev
    volumes:
      - .:/app
    depends_on:
      - postgres
    ports:
      - 4000:4000
    env_file: .env
  postgres:
    image: postgres:10-alpine
    ports:
      - 5444:5432
    environment:
      POSTGRES_USER: graphql_example
